### ISSUE TITLE
Brazilians in Tech

### ISSUE THREAD

**Issue by carvalhomariana** [manifestotech/manifestotech#129]
Empresa:  Brazilians in Tech

Pessoa signatária:  Mariana Carvalho

Cargo ou papel:  Co-Fundadora

URL da empresa sobre sua abordagem do Manifesto: https://braziliansintech.com/

**Comment by sergiolopes** [comment]
Oi Mariana! Obrigado pela submissão! Bem bacana as abordagens de voces!
Vou colocar na proxima leva de grupos signatarios

**Comment by carvalhomariana** [comment]
Obrigada Sergio!!
