### ISSUE TITLE
[Samanta Cicilia] Pagar.me

### ISSUE THREAD

**Issue by samycici** [manifestotech/manifestotech#132]
**Empresa:** Pagar.me

**Pessoa signatária:** Samanta Cicilia

**Cargo ou papel:** Head of Engineering

**Como sua empresa aplica os Princípios do Manifesto hoje?**

- Contratar pessoas em desenvolvimento, e não só as experientes
- Promover cultura de crescimento com aprendizado contínuo.
- Habilitar essas pessoas a entregarem valor em projetos reais.

A Pagar.me é parte do grupo Stone Co. e assim seguimos os mesmos pilares de cultura e posicionamento centrado no desenvolvimento de pessoas.

A busca por profissionais com pouca ou nenhuma experiência sempre foi algo incentivado dentro da cia. Gostamos de trazer pessoas com pouca (ou nenhuma) experiência de mercado, para nós o que mais importa é a identificação com nossa cultura. Aqui escolhemos investir no desenvolvimento dessas pessoas e as tornamos excelentes para o nosso contexto e para o mercado.

**URL da empresa sobre sua abordagem do Manifesto:** https://docs.google.com/document/d/1jJ0QYwPFJfqMftXA7DYsfh24oa3IyXbFCAP3ouFSEJE/edit?usp=sharing

**Post Público sobre apoio ao Manifesto:** https://www.linkedin.com/posts/pagar-me_manifestotech-tecnologia-oportunidades-activity-6909622368919277569-u9XR/

**Comment by ThiagoBarradas** [comment]
Boa Samy!

**Comment by sergiolopes** [comment]
Oi @samycici , @ThiagoBarradas, faz sentido juntar as duas submissões? Pagar.me e Stone? https://github.com/manifestotech/manifestotech/issues/132

O texto daqui aplica pra Stone né? Colocaria no nome de quem?

E, @samycici, acha que consegue publicar em algum blog / linkedin da empresa só pra estar mais público?

**Comment by samycici** [comment]
oi @sergiolopes a gente tá preparando um texto pra publicar nas redes, assim que tiver publicado eu atualizo aqui. Acho que podemos juntar em nome da Stone Co que é o grupo que abrange Stone, Pagarme, Linx e todas as empresas do grupo, o quê vcs acham? @ThiagoBarradas @sergiolopes

**Comment by ThiagoBarradas** [comment]
Acho que podemos submeter uma só em nome do grupo StoneCo, mas também funcionaria fazer pluralizado.

As empresas apesar de serem do mesmo grupo, possuem algumas iniciativas ligadas ao manifesto que são diferentes, nós nos colocamos pro mercado de forma diferente e isso também traria mais apoio a frente da iniciativa.

Inclusive sobre a publicação, conseguimos fazer como PagarMe e como Stone.

Qual sua opinião sobre o melhor formato @sergiolopes?

Acredito que essa visão sua como parte da iniciativa do **manifestotech** seja decisiva pra gente definir o como seguimos.

**Comment by samycici** [comment]
oi @sergiolopes coloquei o link pro post no linkedin, eu e @ThiagoBarradas conversamos e como as empresas, apesar de fazerem parte do mesmo grupo, tem iniciativas e posicionamento de marca em mercado diferente, achamos melhor seguir com duas assinaturas mesmo. Podemos seguir assim?

**Comment by ThiagoBarradas** [comment]
Exato! Como stone o artigo também esta saindo do forno e em breve no ar :)

**Comment by sergiolopes** [comment]
Excelente pessoal! Seguimos com duas, faz todo sentido. Já subi o post da Pagar.me, deve aparecer no site ainda hoje

Obrigado pelo apoio e participação ❤️
