### ISSUE TITLE
Prototipando a Quebrada

### ISSUE THREAD

**Issue by jeffprototipandoaquebrada** [manifestotech/manifestotech#135]
Empresa: Prototipando a Quebrada

Pessoa signatária: Jefferson Lima

Cargo ou papel: CEO e Fundador da ONG

URL da empresa sobre sua abordagem do Manifesto:

**Comment by sergiolopes** [comment]
Bem legal Jeferson, vou linkar pro sote de voces que acho que ja explica bem o intuito do projeto e como abordam as oportunidades para novas pessoas, ok? https://prototipandoaquebrada.org/
