### ISSUE TITLE
ANIMA EDUCAÇÃO

### ISSUE THREAD

**Issue by joaotalles** [manifestotech/manifestotech#143]
Empresa: 
Ânima Educação

Pessoa signatária: 
Patrícia Fumagali 

Cargo ou papel: 
VP Transformação Digital

URL da empresa sobre sua abordagem do Manifesto: 
https://transformacaodigital.animaeducacao.com.br/
https://trabalheconosco.vagas.com.br/animaeducacao

**Comment by sergiolopes** [comment]
Oi @joaotalles, estamos subindo vocês lá no site na leva de agora.
Obrigado pelo apoio ao Manifesto
Abraço

**Comment by joaotalles** [comment]
Muito obrigado Sérgio.

Grato

João Talles
