### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by agelumba** [manifestotech/manifestotech#150]
Empresa: Oracle

Pessoa signatária: Daniele Botaro

Cargo ou papel: Diretora de Diversidade e Inclusão para a Oracle na América Latina

URL da empresa sobre sua abordagem do Manifesto: https://blogs.oracle.com/oracle-brasil/post/por-que-a-oracle-assinou-o-manifesto-tech

**Comment by sergiolopes** [comment]
no ar!
obrigado pela assinatura
