### ISSUE TITLE
Correção de texto em FAQ > seção 4 > essencias

### ISSUE THREAD

**Issue by rkoyanagui** [manifestotech/manifestotech#23]
Atual: `essencias`.

Possíveis correções:

- talvez `essências`
- mais provavelmente `essenciais`

Isso é no último parágrafo da seção FAQ, item 4:

*A inclusão de grupos sub-representados leva a um futuro mais justo. Mas vamos além: times, empresas e o mercado com mais diversidade, são **essencias** para resolver os desafios mais complexos do mundo da tecnologia.*

**Comment by sergiolopes** [comment]
corrigido, obrigado!
