### ISSUE TITLE
[André Coelho] Techzei

### ISSUE THREAD

**Issue by acgrafic** [manifestotech/manifestotech#34]
Empresa: Techzei

Pessoa signatária:  André Coelho

Cargo ou papel: CEO

Como sua empresa aplica os Princípios do Manifesto hoje?
Somos a primeira aceleradora de novos talentos de tecnologia (techzei.com.br). Apoiamos a inclusão de pessoas com pouca ou nenhuma experiência no mercado de tecnologia e aceleramos a sua evolução através de mentorias e imersões práticas. Também apoiamos empresas que queiram contratar novos talentos para que possam desenvolve-los com maior agilidade.

**Comment by sergiolopes** [comment]
Obrigado pela submissao André, vou colocar vocês no site hoje ainda
