### ISSUE TITLE
[SIGNATÁRIO] BLUESOFT

### ISSUE THREAD

**Issue by andrefaria** [manifestotech/manifestotech#42]
Empresa: Bluesoft

Pessoa signatária: André Faria

Cargo ou papel: CEO

Como sua empresa aplica os Princípios do Manifesto hoje?
Temos o MovimentoCodar.org onde todos os anos fazemos um programa gratuito com treinamentos e mentorias, e ao final contratamos parte dos alunos. No último ano (2021) impactamos 20 jovens e contratamos 5, os demais agora estão preparados para o ir para o mercado. Faz parte do Programa receber conta grátis do Alura, Mentoria de desenvolvedores experientes, Webminars, Live Coding e participam Dojos.

Nesse vídeo fala sobre o programa que já está indo para o 4º ano:
https://www.youtube.com/watch?v=nZd6Bl7ofyo

**Comment by sergiolopes** [comment]
Oi @andrefaria! Obrigado pelo apoio ao Manifesto e fazer parte com a gente. Vou subir no site a assinatura de voces e linkar para o vídeo que vc mandou.

As empresas têm mandado algum posicionamento publico relacionado aos principios do Manifesto (se quiser ver outros exemplos no site). Vou linkar o vídeo que vc mandou no caso de vcs mas se quiser fazer algum outro texto avisa aqui

Abraço

**Comment by andrefaria** [comment]
Woo hoo! uma honra, @sergiolopes! Obrigado.
