### ISSUE TITLE
[SIGNATÁRIO] Grupo FCamara

### ISSUE THREAD

**Issue by mariana-mendanha** [manifestotech/manifestotech#48]
Empresa: Grupo FCamara

Pessoa signatária: Fabio Camara

Cargo ou papel: CEO

Como sua empresa aplica os Princípios do Manifesto hoje?
Líder no desenvolvimento de soluções digitais, o Grupo FCamara é constituído por uma premiada empresa de tecnologia e uma venture builder que já fundou 8 startups, atingindo escala global. Formação está em seu DNA, sua razão social, na sua cultura. Por isso, desde 2017, temos o Programa de Formação, um processo seletivo que busca trazer novas pessoas que querem começar na área de tecnologia e que não tenha experiência profissional, para inseri-las no mercado de trabalho. Uma oportunidade única para o desenvolvimento de carreira e traçar uma história, sendo protagonista. [https://fcamara.com.br/programa-formacao](Para saber mais)

**Comment by sergiolopes** [comment]
Oi @mariana-mendanha, obrigado pelo apoio de voces ao Manifesto! Vou subir hoje ainda no site a assinatura de vocês.

As empresas têm mandado algum posicionamento público relacionado aos principios do Manifesto (um texto, post, video, até podcast). No caso de voces vou linkar para o Programa de Formacao que vc mandou, mas se quiser mandar um outro texto, me avisa.

Alguns exemplos do que pessoal tem colocado:

https://www.alura.com.br/manifesto-tech
https://medium.com/inside-picpay/por-que-o-picpay-assinou-o-manifestotech-bf0ccd281373
https://www.lambda3.com.br/2022/02/lambda3-podcast-esp02-manifesto-tech-e-lambda3/
https://campuscode.com.br/conteudos/porque-apoiamos-o-manifesto-tech
https://www.linkedin.com/feed/update/urn:li:activity:6905620691664920576/
https://www.linkedin.com/posts/pagar-me_manifestotech-tecnologia-oportunidades-activity-6909622368919277569-u9XR/
https://blog.stone.com.br/nossa-historia-e-nosso-apoio-ao-manifesto-tech/
