### ISSUE TITLE
[SIGNATÁRIO] Zup

### ISSUE THREAD

**Issue by mariogalvao** [manifestotech/manifestotech#54]
Empresa: Zup 

Pessoa signatária: Mário Henrique Casari Galvão 

Cargo ou papel: Head of Technology 

Como sua empresa aplica os Princípios do Manifesto hoje? Bootcamp de 3 meses remunerado para desenvolvedores em início de carreira.

**Comment by sergiolopes** [comment]
Oi Mario! A Zup ta lá já! Fantástico o trabalho de voces com o Orange Talents!
