### ISSUE TITLE
[Alexandre Freire] Sami Saúde

### ISSUE THREAD

**Issue by alexandrefreire** [manifestotech/manifestotech#62]
Empresa: Sami Saúde

Pessoa signatária: Alexandre Freire

Cargo ou papel: CTO

Como sua empresa aplica os Princípios do Manifesto hoje?

18% do nosso corpo técnico é composto por pessoas Junior. queremos manter esse número próximo de 20% proporcionando um caminho de entrada na indústria e muito apoio. além de termos benefícios como cursos de inglês e bibliotecas de cursos técnicos temos como principais valores da empresa "curtimos, compartilhamos e ajudamos" e "melhoramos a cada dia". Nosso projetos usam uma stack que evita complexidade, Javascript, NodeJs, bancos de dados SQL, e Flutter. Nossos colaboradores senior e pleno tem a expectativa clara de formar e apoiar a base. Nosso onboarding inclui tempo para adaptação, aprendizado e um programa de companheiros. Nossa cultura permite tempo para estudar e se aprimorar durante o expediente. Trabalhamos com parcerias com programas de formação e criação de oportunidades para pessoas de segmentos sociais sub representados em tecnologia.

**Comment by sergiolopes** [comment]
Oi @alexandrefreire, fechando aqui, que já subimos a Sami no site há algumas semanas!
Abraço e obrigado por apoiar o Manifesto com a gente
